services:
  api:
    build: ./api
    container_name: notes-api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/notesdb

  mongodb:
    image: mongo:6
    container_name: notes-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
